import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/Navbar';
import { Toaster } from '@/components/ui/sonner';
import GridBackground from '@/components/layouts/GridBackground';

export const metadata: Metadata = {
  title: 'Revume',
  description: 'Generated by Ruumaa',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative w-full min-h-screen overflow-hidden">
          <GridBackground />
          <div className="absolute flex items-center justify-center top-10 w-full">
            <Navbar />
          </div>
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
