import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/Navbar';
import { Toaster } from '@/components/ui/sonner';
import GridBackground from '@/components/layouts/GridBackground';
import { Inter, Montserrat, Pixelify_Sans } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Revume',
  description: 'Generated by Ruumaa',
};

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});
const pixelify_sans = Pixelify_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pixelify-sans',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${inter.variable} ${pixelify_sans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <div className="relative w-full min-h-screen overflow-hidden">
          <GridBackground />
          <div className="absolute flex items-center justify-center top-10 w-full">
            <Navbar />
          </div>
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
